#!/usr/bin/env node
// Generate config.js from .env for static hosting: npm run config
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { readEnv } from './env.mjs';

const env = await readEnv();
const body = `window.__RECEIPT_OCR_CONFIG__ = ${JSON.stringify(
  { geminiApiKey: env.GEMINI_API_KEY || '', geminiModel: env.GEMINI_MODEL || '' },
  null,
  2,
)};\n`;
await writeFile(resolve('config.js'), `// Generated by npm run config — do not commit.\n${body}`);
console.log(
  env.GEMINI_API_KEY
    ? 'config.js written with a Gemini key — do not commit it.'
    : 'config.js written (no GEMINI_API_KEY found in .env).',
);
